//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Explore"",
            ""id"": ""1a9d8d92-4ef3-4293-9aae-ff1aeddd3a80"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8816a9bf-fc55-4fd5-8f36-68011cde0db6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""ab4b57c3-57d9-4e37-8077-135e88db2107"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""4900869d-a64b-48bd-b7f8-ad1673498e76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""b75b24b5-c6aa-4edc-8158-4dff4ec2b59f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseTool"",
                    ""type"": ""Button"",
                    ""id"": ""1742d281-72e7-4e7c-b31c-67f63d2cd03d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextTool"",
                    ""type"": ""Button"",
                    ""id"": ""b95d33fe-6999-4abd-b732-e10786da84ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevTool"",
                    ""type"": ""Button"",
                    ""id"": ""b8ac4cb3-be06-493d-bb40-7629928198cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FirstTool"",
                    ""type"": ""Button"",
                    ""id"": ""9de0116f-b9bf-4896-a129-25f0fab89c2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondTool"",
                    ""type"": ""Button"",
                    ""id"": ""d9bffc16-e059-4e30-87eb-f0ef2ffe8d28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThirdTool"",
                    ""type"": ""Button"",
                    ""id"": ""3c782897-47e9-4c6d-8000-1f4f9e457c36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourthTool"",
                    ""type"": ""Button"",
                    ""id"": ""2b8af585-5926-4865-b655-167e4e1d1784"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""3b215262-54db-4537-a357-4d40a4239664"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fefea7db-b7ec-4f4f-9253-36ebe3bbead9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""12af15fa-b6ae-4018-a32b-833665d2e24e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""361e3b2e-b2ee-4b7e-bd1b-3db3cee35dfc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""97e92e01-0fea-42ab-ab28-760d85b865fb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d998bce3-0d79-49af-bc5c-5236d2eeb491"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""16119bca-0c3e-4771-bf15-a197b7c58cab"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""17f9c12b-a35b-46f2-b5a8-bd8c6bef01b5"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa2a5d45-719f-4025-963a-98ff9fbe9e4e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb02097e-dcec-4f58-8fea-d2462ce9fe56"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cea918d-2f64-476c-9e54-52e706188954"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dbf8dc2-3bc3-4bf7-ad43-94afeda454cf"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3efb77d-f352-415f-94c1-26d81885ce82"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02c07a73-705a-4477-88d7-dbdea5f68237"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd314961-6f70-48a3-a4d7-8070ae37c9d8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""834926a3-0dfe-442b-a06a-3a670e24dc65"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc3ee7ea-17ec-4efe-b94e-41d64c42daba"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0dee4d5-5b29-4571-b887-8df0466678e2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""167f1732-a21e-4d5d-bf4a-35982d4a43a5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5e0cf9e-e44e-4d78-9036-f9b996a866ed"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd836a00-de56-4154-8b4b-11ae48068106"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bb4796a-b7ac-46fe-9afd-8812c08f80e3"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb413f3f-5b0f-4954-90e2-cc5fd8db71a0"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThirdTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""249c3ca4-1378-436f-8e18-4ec371a9c59c"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourthTool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bf906d2-54e1-4134-8b6f-b1966af4bb06"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4c344fb-2327-4830-bffe-1e4d5a26470f"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""410941d1-10bf-4c59-98f2-64772b9f6428"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Explore
        m_Explore = asset.FindActionMap("Explore", throwIfNotFound: true);
        m_Explore_Move = m_Explore.FindAction("Move", throwIfNotFound: true);
        m_Explore_Jump = m_Explore.FindAction("Jump", throwIfNotFound: true);
        m_Explore_Sprint = m_Explore.FindAction("Sprint", throwIfNotFound: true);
        m_Explore_Interact = m_Explore.FindAction("Interact", throwIfNotFound: true);
        m_Explore_UseTool = m_Explore.FindAction("UseTool", throwIfNotFound: true);
        m_Explore_NextTool = m_Explore.FindAction("NextTool", throwIfNotFound: true);
        m_Explore_PrevTool = m_Explore.FindAction("PrevTool", throwIfNotFound: true);
        m_Explore_FirstTool = m_Explore.FindAction("FirstTool", throwIfNotFound: true);
        m_Explore_SecondTool = m_Explore.FindAction("SecondTool", throwIfNotFound: true);
        m_Explore_ThirdTool = m_Explore.FindAction("ThirdTool", throwIfNotFound: true);
        m_Explore_FourthTool = m_Explore.FindAction("FourthTool", throwIfNotFound: true);
        m_Explore_Menu = m_Explore.FindAction("Menu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Explore
    private readonly InputActionMap m_Explore;
    private IExploreActions m_ExploreActionsCallbackInterface;
    private readonly InputAction m_Explore_Move;
    private readonly InputAction m_Explore_Jump;
    private readonly InputAction m_Explore_Sprint;
    private readonly InputAction m_Explore_Interact;
    private readonly InputAction m_Explore_UseTool;
    private readonly InputAction m_Explore_NextTool;
    private readonly InputAction m_Explore_PrevTool;
    private readonly InputAction m_Explore_FirstTool;
    private readonly InputAction m_Explore_SecondTool;
    private readonly InputAction m_Explore_ThirdTool;
    private readonly InputAction m_Explore_FourthTool;
    private readonly InputAction m_Explore_Menu;
    public struct ExploreActions
    {
        private @PlayerInputAction m_Wrapper;
        public ExploreActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Explore_Move;
        public InputAction @Jump => m_Wrapper.m_Explore_Jump;
        public InputAction @Sprint => m_Wrapper.m_Explore_Sprint;
        public InputAction @Interact => m_Wrapper.m_Explore_Interact;
        public InputAction @UseTool => m_Wrapper.m_Explore_UseTool;
        public InputAction @NextTool => m_Wrapper.m_Explore_NextTool;
        public InputAction @PrevTool => m_Wrapper.m_Explore_PrevTool;
        public InputAction @FirstTool => m_Wrapper.m_Explore_FirstTool;
        public InputAction @SecondTool => m_Wrapper.m_Explore_SecondTool;
        public InputAction @ThirdTool => m_Wrapper.m_Explore_ThirdTool;
        public InputAction @FourthTool => m_Wrapper.m_Explore_FourthTool;
        public InputAction @Menu => m_Wrapper.m_Explore_Menu;
        public InputActionMap Get() { return m_Wrapper.m_Explore; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ExploreActions set) { return set.Get(); }
        public void SetCallbacks(IExploreActions instance)
        {
            if (m_Wrapper.m_ExploreActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnJump;
                @Sprint.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnSprint;
                @Interact.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnInteract;
                @UseTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnUseTool;
                @UseTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnUseTool;
                @UseTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnUseTool;
                @NextTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnNextTool;
                @NextTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnNextTool;
                @NextTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnNextTool;
                @PrevTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnPrevTool;
                @PrevTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnPrevTool;
                @PrevTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnPrevTool;
                @FirstTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnFirstTool;
                @FirstTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnFirstTool;
                @FirstTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnFirstTool;
                @SecondTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnSecondTool;
                @SecondTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnSecondTool;
                @SecondTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnSecondTool;
                @ThirdTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnThirdTool;
                @ThirdTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnThirdTool;
                @ThirdTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnThirdTool;
                @FourthTool.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnFourthTool;
                @FourthTool.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnFourthTool;
                @FourthTool.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnFourthTool;
                @Menu.started -= m_Wrapper.m_ExploreActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_ExploreActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_ExploreActionsCallbackInterface.OnMenu;
            }
            m_Wrapper.m_ExploreActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @UseTool.started += instance.OnUseTool;
                @UseTool.performed += instance.OnUseTool;
                @UseTool.canceled += instance.OnUseTool;
                @NextTool.started += instance.OnNextTool;
                @NextTool.performed += instance.OnNextTool;
                @NextTool.canceled += instance.OnNextTool;
                @PrevTool.started += instance.OnPrevTool;
                @PrevTool.performed += instance.OnPrevTool;
                @PrevTool.canceled += instance.OnPrevTool;
                @FirstTool.started += instance.OnFirstTool;
                @FirstTool.performed += instance.OnFirstTool;
                @FirstTool.canceled += instance.OnFirstTool;
                @SecondTool.started += instance.OnSecondTool;
                @SecondTool.performed += instance.OnSecondTool;
                @SecondTool.canceled += instance.OnSecondTool;
                @ThirdTool.started += instance.OnThirdTool;
                @ThirdTool.performed += instance.OnThirdTool;
                @ThirdTool.canceled += instance.OnThirdTool;
                @FourthTool.started += instance.OnFourthTool;
                @FourthTool.performed += instance.OnFourthTool;
                @FourthTool.canceled += instance.OnFourthTool;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
            }
        }
    }
    public ExploreActions @Explore => new ExploreActions(this);
    public interface IExploreActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnUseTool(InputAction.CallbackContext context);
        void OnNextTool(InputAction.CallbackContext context);
        void OnPrevTool(InputAction.CallbackContext context);
        void OnFirstTool(InputAction.CallbackContext context);
        void OnSecondTool(InputAction.CallbackContext context);
        void OnThirdTool(InputAction.CallbackContext context);
        void OnFourthTool(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
    }
}
